# Generated by Django 4.1.3 on 2022-11-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='priority',
            field=models.TextField(default='high'),
            preserve_default=False,
        ),
    ]
