# Generated by Django 4.1.4 on 2022-12-07 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todolistitem_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='area',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
